management:
  endpoints:
    web:
      exposure:
        include: health,info,httptrace,loggers,metrics,prometheus
  endpoint:
    health:
      show-details: always
  info:
    git:
      mode: full

cron:
  collection: "0 0 0 * * *"

---
spring:
  profiles: cloud

management:
  cloudfoundry:
    enabled: true
    skip-ssl-validation: true

